import Foundation

// MARK: - MessageRole

/// The role of a message in a conversation, indicating who or what
/// generated the message content.
@frozen
enum MessageRole: String, Codable, CaseIterable {
    /// A message sent by the human user.
    case user

    /// A message generated by the AI assistant.
    case assistant

    /// A system-level message that sets behavior context.
    case system

    /// A message representing the result of a tool execution.
    case tool
}

// MARK: - TokenUsage

/// Tracks token consumption for a single message or API call.
struct TokenUsage: Codable, Equatable {

    /// The number of input tokens consumed.
    let inputTokens: Int

    /// The number of output tokens generated.
    let outputTokens: Int

    /// The total number of tokens consumed (input + output).
    var totalTokens: Int {
        inputTokens + outputTokens
    }

    init(inputTokens: Int = 0, outputTokens: Int = 0) {
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
    }
}

// MARK: - ToolCall

/// Represents a tool invocation requested by the AI assistant.
///
/// A tool call includes the tool name and its arguments encoded as
/// a JSON string, matching the Anthropic/OpenAI tool-use format.
struct ToolCall: Codable, Equatable {

    /// Unique identifier for this tool call instance.
    let id: String

    /// The name of the tool being invoked.
    let name: String

    /// JSON-encoded string of arguments passed to the tool.
    let arguments: String

    init(id: String = UUID().uuidString, name: String, arguments: String = "{}") {
        self.id = id
        self.name = name
        self.arguments = arguments
    }
}

// MARK: - Message

/// A single message within a conversation.
///
/// Messages can originate from users, the AI assistant, the system,
/// or represent tool execution results. Each message tracks its
/// role, content, optional tool calls, and token usage statistics.
struct Message: Codable, Identifiable, Equatable {

    // MARK: - Properties

    /// Unique identifier for the message.
    let id: UUID

    /// The role indicating who generated this message.
    let role: MessageRole

    /// The textual content of the message.
    var content: String

    /// Tool calls requested by the assistant within this message.
    /// Present only when `role` is `.assistant` and the agent
    /// invokes tools.
    var toolCalls: [ToolCall]?

    /// When this message is a tool result, the ID of the tool call
    /// it responds to. `nil` for non-tool messages.
    var toolCallId: String?

    /// Timestamp of when this message was created.
    let timestamp: Date

    /// Token usage statistics for this message, if available.
    var tokenUsage: TokenUsage?

    // MARK: - Initialization

    init(
        id: UUID = UUID(),
        role: MessageRole,
        content: String = "",
        toolCalls: [ToolCall]? = nil,
        toolCallId: String? = nil,
        timestamp: Date = Date(),
        tokenUsage: TokenUsage? = nil
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.toolCalls = toolCalls
        self.toolCallId = toolCallId
        self.timestamp = timestamp
        self.tokenUsage = tokenUsage
    }
}
